# -*- coding: utf-8 -*-
# Correct lesson data: lesson_number -> (video_id, title, series)
# OUTER number (filename) = truth. INNER numbers from DOCX were wrong.

LESSONS = {
    1:  ('YeSjdF3noiU',  'Training is Essential', 'MLT'),
    2:  ('MxdoaWZr9D8',  'Spiritual Missionary Leadership', 'MLT'),
    3:  ('hbbK1JsTeLU',  'Sacrificial Leader', 'MLT'),
    4:  ('H2GSDmhykg4',  'Selfless Missionary Leader', 'MLT'),
    5:  ('a0UKml-vrLk',  'Self Discipline Missionary Leader', 'MLT'),
    6:  ('lag7mO65nT8',  'Servant Missionary Leader', 'MLT'),
    7:  ('OxvgGSCbIrk',  'Skilled Missionary Leader', 'MLT'),
    8:  ('1nXd6vDb9oY',  'The Spirit Filled Leader', 'MLT'),
    9:  ('yfvFzKlewQM',  'Submitted Missionary Leader', 'MLT'),
    10: ('jSYNaaDdO3Y',  'Whatever It Takes', 'MLT'),
    11: ('uH4s8b8GooU',  'Imparting Holy Spirit', 'MLT'),
    12: ('tXTPVVoKGlc',  'Keys to Promotion', 'MLT'),
    13: ('VIyRXNFGLhk',  'Extreme Stewardship', 'MLT'),
    14: ('cat4DSxNmC0',  'Nehemiah', 'MLT'),
    15: ('d-upsq0wMC8',  'The 3 Cs', 'MLT'),
    16: ('JjltQ0ESbvw',  'Humility and Honor', 'MLT'),
    17: ('ITeD1Slkr98',  'Task Completed', 'MLT'),
    18: ('8FXd6layaFU',  'Vision 1', 'MLT'),
    19: (None,           'Vision 2', 'MLT'),
    20: (None,           'Vision 3', 'MLT'),
    21: ('jTDzVJsLdxY',  'Cultivating Consistent Prayer', 'MLT'),
    22: ('86kPHfBphv4',  'Preaching and Teaching', 'MLT'),
    23: ('JDXoqhNceaY',  'Self Management', 'MLT'),
    24: ('ROmgdycSxgE',  'Building Credibility', 'MLT'),
    25: (None,           'Failed Leadership', 'MLT'),
    26: ('_a8NUvwD6yE',  'Acts 29 Part 1', 'MLT'),
    27: ('IGOTRx66isY',  'Acts 29 Part 2', 'MLT'),
    28: ('ClfL8-yeWVI',  'Acts 29 Part 3', 'MLT'),
    29: ('53sHimb4OA8',  'Acts 29 Part 4', 'MLT'),
    30: ('hWpWJoUM2sY',  'Building a Team', 'MLT'),
    31: ('iNi8pMGYIac',  'Conflict Resolution Part 1', 'MLT'),
    32: ('5CynIkGiby4',  'Conflict Resolution Part 2', 'MLT'),
    33: ('z5NVcUfeDIE',  'Theology of Planning', 'MLT'),
    34: ('AK7gxWH62EU',  'Building Relationships', 'MLT'),
    35: ('p7VJvEOKtEk',  'Delegation', 'MLT'),
    36: ('KzmtHJ9_VoY',  'Sustaining Strength', 'MLT'),
    37: (None,           'Facing Rejection', 'SLT'),
    38: ('afqpLETI6wE',  'Well Planned Meetings', 'SLT'),
    39: ('_znpfIc48MM',  'Joseph', 'SLT'),
    40: ('5BSw2GZyMf0',  'Leading Change', 'SLT'),
    41: ('nzmvkacTuGs',  'Leaders Make Good Followers', 'SLT'),
    42: ('wxxwohb3f0w',  'Creating Agreement', 'MLT'),
    43: ('8krbDnHDQio',  'Missionary Leader and Health', 'MLT'),
    44: ('VbtPZ8al42Q',  'Revolving Door', 'SLT'),
    45: ('x3PeEyNbIJk',  'Samuel', 'SLT'),
    46: ('_4g7jZoFxDQ',  'Recognizing Seizing Kairos Moments', 'MLT'),
    47: ('cHD7HI6w_3Y',  'Warrior Leader', 'SLT'),
    48: ('Niyd00F9hT4',  'Leaders Task', 'SLT'),
    49: ('JAoAuZdgm-8',  'Reproducer Part 1', 'SLT'),
    50: ('Do1KRrb707A',  'Reproducer Part 2', 'SLT'),
}

# Duplicate videos (NOT used - same topic, wrong numbering)
DUPLICATES = {
    'jlm_GcWBlhI': 'Duplicate of lesson 43 (Missionary Leader and Health)',
    'ZruI4zyP5eA': 'Duplicate of lesson 46 (Recognizing Seizing Kairos)',
    '9b-AQVppgCk': 'SLT46 - no matching DOCX found',
}
