# -*- coding: utf-8 -*-
# Correct lesson data: lesson_number -> (video_id, title, series)
# OUTER number (filename) = truth. INNER numbers from DOCX were wrong.

LESSONS = {
    1:  ('YeSjdF3noiU',  'Training is Essential', 'MLT'),
    2:  ('MxdoaWZr9D8',  'Spiritual Missionary Leadership', 'MLT'),
    3:  ('hbbK1JsTeLU',  'Sacrificial Leader', 'MLT'),
    4:  ('H2GSDmhykg4',  'Selfless Missionary Leader', 'MLT'),
    5:  ('a0UKml-vrLk',  'Self Discipline Missionary Leader', 'MLT'),
    6:  ('lag7mO65nT8',  'Servant Missionary Leader', 'MLT'),
    7:  ('OxvgGSCbIrk',  'Skilled Missionary Leader', 'MLT'),
    8:  ('1nXd6vDb9oY',  'The Spirit Filled Leader', 'MLT'),
    9:  ('yfvFzKlewQM',  'Submitted Missionary Leader', 'MLT'),
    10: ('jSYNaaDdO3Y',  'Whatever It Takes', 'MLT'),
    11: ('uH4s8b8GooU',  'Imparting Holy Spirit', 'MLT'),
    12: ('tXTPVVoKGlc',  'Keys to Promotion', 'MLT'),
    13: ('VIyRXNFGLhk',  'Extreme Stewardship', 'MLT'),
    14: ('cat4DSxNmC0',  'Nehemiah', 'MLT'),
    15: ('d-upsq0wMC8',  'The 3 Cs', 'MLT'),
    16: ('JjltQ0ESbvw',  'Humility and Honor', 'MLT'),
    17: ('ITeD1Slkr98',  'Task Completed', 'MLT'),
    18: ('8FXd6layaFU',  'Vision 1', 'MLT'),
    19: ('aEog1gS76sw',  'Vision 2', 'MLT'),
    20: ('nRhAl9C2JNk',  'Vision 3', 'MLT'),
    21: ('BX81qiCyOyg',  'Cultivating Consistent Prayer', 'MLT'),
    22: ('f0USEWs8fDM',  'Preaching and Teaching', 'MLT'),
    23: ('JDXoqhNceaY',  'Self Management', 'MLT'),
    24: ('3p6tisxAOmY',  'Building Credibility', 'MLT'),
    25: ('26-swxfEXg8',  'Failed Leadership', 'MLT'),
    26: ('jTDzVJsLdxY',  'Acts 29 Part 1', 'MLT'),
    27: ('IGOTRx66isY',  'Acts 29 Part 2', 'MLT'),
    28: ('53sHimb4OA8',  'Acts 29 Part 3', 'MLT'),
    29: ('_a8NUvwD6yE',  'Acts 29 Part 4', 'MLT'),
    30: ('hWpWJoUM2sY',  'Building a Team', 'MLT'),
    31: ('sOPaZdfeXag',  'Conflict Resolution Part 1', 'MLT'),
    32: ('5CynIkGiby4',  'Conflict Resolution Part 2', 'MLT'),
    33: ('rtZjkXMYYa8',  'Theology of Planning', 'MLT'),
    34: ('Rdqw0JrJiiY',  'Building Relationships', 'MLT'),
    35: ('p7VJvEOKtEk',  'Delegation', 'MLT'),
    36: ('KzmtHJ9_VoY',  'Sustaining Strength', 'MLT'),
    37: ('yeIQXWbjMPk',  'Facing Rejection', 'SLT'),
    38: ('PX3TgeCJL4U',  'Leaders Make Disciples', 'SLT'),
    39: ('2Lbg1wRwmH8',  'Joseph', 'SLT'),
    40: ('td8I0DmA-p4',  'Leading Change', 'SLT'),
    41: ('PDpoXKx8t1w',  'Leaders Make Good Followers', 'SLT'),
    42: ('8Dvaj-I5A2A',  'Creating Agreement', 'MLT'),
    43: ('8krbDnHDQio',  'Missionary Leader and Health', 'MLT'),
    44: ('_rnqowVAGv4',  'Revolving Door', 'SLT'),
    45: ('LyFX9NxJMQo',  'Samuel', 'SLT'),
    46: ('_4g7jZoFxDQ',  'Recognizing Seizing Kairos Moments', 'MLT'),
    47: ('D6fjdWejh7A',  'Warrior Leader', 'SLT'),
    48: ('d385fdRQrQQ',  'Leaders Task', 'SLT'),
    49: ('3KgD0gYaMBo',  'Reproducer Part 1', 'SLT'),
    50: ('AynxSZLq4gg',  'Reproducer Part 2', 'SLT'),
}

# Old/replaced videos (no longer used)
REPLACED = {
    'WbB-eDeRTDg': 'Old lesson 19 (Vision 2)',
    'ROmgdycSxgE': 'Old lesson 24 (Building Credibility)',
    'ZrIoQiOtbsI': 'Old lesson 25 (Failed Leadership)',
    'ClfL8-yeWVI': 'Old lesson 28 (Acts 29 Part 3)',
    'iNi8pMGYIac': 'Old lesson 31 (Conflict Resolution Part 1)',
    'z5NVcUfeDIE': 'Old lesson 33 (Theology of Planning)',
    'BMDVWodnF-Q': 'Old lesson 37 (Facing Rejection)',
    'A66f6LUuuZ8': 'Old lesson 38 (Leaders Make Disciples)',
    '_znpfIc48MM': 'Old lesson 39 (Joseph)',
    '5BSw2GZyMf0': 'Old lesson 40 (Leading Change)',
    'nzmvkacTuGs': 'Old lesson 41 (Leaders Make Good Followers)',
    'wxxwohb3f0w': 'Old lesson 42 (Creating Agreement)',
    'VbtPZ8al42Q': 'Old lesson 44 (Revolving Door)',
    'x3PeEyNbIJk': 'Old lesson 45 (Samuel)',
    'cHD7HI6w_3Y': 'Old lesson 47 (Warrior Leader)',
    'Niyd00F9hT4': 'Old lesson 48 (Leaders Task)',
    'JAoAuZdgm-8': 'Old lesson 49 (Reproducer Part 1)',
    'Do1KRrb707A': 'Old lesson 50 (Reproducer Part 2)',
}

# Duplicate videos (NOT used - same topic, wrong numbering)
DUPLICATES = {
    'jlm_GcWBlhI': 'Duplicate of lesson 43 (Missionary Leader and Health)',
    'ZruI4zyP5eA': 'Duplicate of lesson 46 (Recognizing Seizing Kairos)',
    '9b-AQVppgCk': 'SLT46 - no matching DOCX found',
}